name: Android Test

on:
  workflow_call:

env:
  JAVA_VERSION: 17
  GRADLE_VERSION: 8.8

jobs:
  android-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [23, 26, 30]
      fail-fast: false
    timeout-minutes: 30
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", 
          OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Android test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: 'google_apis'
          arch: 'x86'
          profile: 'pixel'
          disable-animations: true
          script: ./gradlew connectedMockDebugAndroidTest