name: Android Test

on:
  workflow_call:
    secrets:
      API_KEY:
        required: true

env:
  JAVA_VERSION: 17
  GRADLE_VERSION: 8.8

jobs:
  androidTest:
    runs-on: macOS-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [34]

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Create local.properties
        run: |
          cat << EOF > local.properties
          sdk.dir=$ANDROID_HOME
          API_KEY=${{ secrets.API_KEY }}
          EOF
          echo "Created local.properties file"

      - name: Run Android test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: 'google_apis'
          arch: 'x86'
          profile: 'pixel'
          disable-animations: true
          disk-size: 6000M
          heap-size: 600M
          script: ./gradlew connectedAndroidTest

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.api-level }}
          path: '**/build/reports/androidTests'