name: Android Test

on:
  workflow_call:
    secrets:
      API_KEY:
        required: true

env:
  JAVA_VERSION: 17
  GRADLE_VERSION: 8.8

jobs:
  androidTest:
    runs-on: macOS-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [34]

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Prepare Environment
        run: |
          chmod +x ./gradlew
          echo "API_KEY=${{ secrets.API_KEY }}" > local.properties
          echo "Created local.properties file"

      - name: Install Android SDK Command-Line Tools
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk
          sudo chmod -R 777 /usr/local/lib/android/sdk
          curl -Lo sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip sdk-tools.zip -d /usr/local/lib/android/sdk/cmdline-tools
          mv /usr/local/lib/android/sdk/cmdline-tools/cmdline-tools /usr/local/lib/android/sdk/cmdline-tools/latest
          rm sdk-tools.zip

      - name: Set Environment Variables
        run: |
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Update SDK Tools
        run: sdkmanager --update

      - name: Install required SDK packages
        run: |
          sdkmanager "platforms;android-34" 
          sdkmanager "build-tools;34.0.0"
          sdkmanager "system-images;android-34;google_apis;x86_64"

      - name: Run Android test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: 'google_apis'
          arch: 'x86'
          profile: 'pixel'
          disable-animations: true
          disk-size: 6000M
          heap-size: 600M
          script: ./gradlew connectedAndroidTest

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.api-level }}
          path: '**/build/reports/androidTests'