name: Detekt Analysis

on:
  workflow_call:

jobs:
  detekt:
    name: Detekt Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Restore Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Prepare Environment
        run: |
          chmod +x ./gradlew
          echo "API_KEY=${{ secrets.API_KEY }}" > local.properties

      - name: Run Detekt
        run: ./gradlew detekt
        continue-on-error: true

      - name: Setup Reviewdog
        if: always()
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run Reviewdog for Detekt
        if: always()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f ./build/reports/detekt.xml ]; then
            cat ./build/reports/detekt.xml | reviewdog -f=checkstyle -name="detekt" -reporter="github-pr-review"
          fi

      - name: Comment on PR - Detekt Results
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## ⚠️ Detekt Issues Found\n\nDetektで静的解析の問題が検出されました。上記のコードレビューコメントで詳細を確認してください。\n\n[ワークフローの詳細を見る](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})'
            });
