name: Unit Tests

on:
  workflow_call:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Restore Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Prepare Environment
        run: |
          chmod +x ./gradlew
          echo "API_KEY=${{ secrets.API_KEY }}" > local.properties

      - name: Download Build Artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-outputs

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --parallel
        continue-on-error: true

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: "JUnit Test Report"
          path: '**/build/test-results/*/TEST-*.xml'
          reporter: 'java-junit'
          fail-on-error: false

      - name: Comment on PR - Test Results
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## ❌ Unit Tests Failed\n\n単体テストでエラーが発生しました。詳細なテスト結果は上記のTest Reportを確認してください。\n\n[ワークフローの詳細を見る](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})'
            });
